channels:
  - conda-forge
  - usgs-astrogeology
  - menpo

dependencies:
  - python>=3
  - coveralls
  - csmapi
  - cyvlfeat
  - dill
  - geoalchemy2
  - geopandas
  - hoggorm
  - imageio
  - ipykernel
  - jupyter
  - knoten>= 0.2.0,<1.0
  - ncurses
  - networkx >=2, <3
  - numpy
  - opencv <= 3.5
  - pillow
  - pip
  - plio>=1.3
  - plurmy
  - psycopg2
  - proj>=7.0.0,<8
  - pyproj
  - pytest
  - pytest-cov
  - pysis
  - richdem
  - scikit-image>=0.17
  - scikit-learn
  - scipy<=1.2.1
  - shapely
  - sqlalchemy>=1.4,<1.5
  - sqlalchemy-utils>=0.37.0
  - redis-py
  - usgscsm
  - vlfeat
